package com.despegar.cars;

public enum States {
	INIT, 
	TASK_GEN_ID, 
	TASK_RISK,
	CHOICE_RISK,
	TASK_RISK_IN_PROGRESS, 
	TASK_RISK_REJECT, 
	TASK_BOOKING,
	CHOICE_BOOKING,
	TASK_BOOKING_ERROR, 
	TASK_VALIDATE_COUPON,
	CHOICE_VALIDATE_COUPON,
	TASK_VALIDATE_COUPON_OK,
	TASK_OFFLINE,
	FORK_COLLECT_GEN_VOUCHER,
	TASKS_COLLECT_GEN_VOUCHER,
	TASK_COLLECT,
	TASK_GEN_VOUCHER,
	TASK_END_COLLECT,
	TASK_END_GEN_VOUCHER,
	JOIN_COLLECT_GEN_VOUCHER,
	CHOICE_COLLECT_GEN_VOUCHER,
	TASK_NEW_CC, 
	TASK_FINALIZED,
	END
}
